### ISSUE TITLE
Run Time Injection Problems

### ISSUE THREAD

**Issue by DwayneSmurdon** [unterstein/play-neo4j-template#1]
Hello @unterstein,

Starting last night, I'm getting some Injection (I believe) issues and I'm not entirely sure even how to debug/troubleshoot it.  Any help you can provide would be appreciated. 
## Here's the error and my build.sbt contents are below that:

[error] - application -

! @6pi3ll2pl - Internal server error, for (GET) [/load/ref/csz] ->

play.api.UnexpectedException: Unexpected exception[ProvisionException: Unable to provision, see the following errors:

1) No primary bean definition for type: interface neo4j.repositories.AddressCharacteristicRepository
  at org.springframework.guice.module.SpringModule.bindConditionally(SpringModule.java:88) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.SpringNeo4jModule)
  while locating neo4j.repositories.AddressCharacteristicRepository
    for field at controllers.loaders.ImportService.addressRepository(ImportService.java:48)
  while locating controllers.loaders.ImportService
    for field at controllers.loaders.DataLoader.importService(DataLoader.java:25)
  while locating controllers.loaders.DataLoader
    for parameter 4 at router.Routes.<init>(Routes.scala:48)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for parameter 0 at play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:200)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for parameter 4 at play.api.DefaultApplication.<init>(Application.scala:220)
  at play.api.DefaultApplication.class(Application.scala:220)
  while locating play.api.DefaultApplication
  while locating play.api.Application

2) No primary bean definition for type: interface neo4j.repositories.AddressCharacteristicRepository
  at org.springframework.guice.module.SpringModule.bindConditionally(SpringModule.java:88) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.SpringNeo4jModule)
  while locating neo4j.repositories.AddressCharacteristicRepository
    for field at controllers.loaders.ImportService.addressRepository(ImportService.java:48)
  while locating controllers.loaders.ImportService
    for field at controllers.loaders.LoadAll.importService(LoadAll.java:33)
  while locating controllers.loaders.LoadAll
    for parameter 5 at router.Routes.<init>(Routes.scala:48)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for parameter 0 at play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:200)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for parameter 4 at play.api.DefaultApplication.<init>(Application.scala:220)
  at play.api.DefaultApplication.class(Application.scala:220)
  while locating play.api.DefaultApplication
  while locating play.api.Application

3) No primary bean definition for type: interface neo4j.repositories.AddressCharacteristicRepository
  at org.springframework.guice.module.SpringModule.bindConditionally(SpringModule.java:88) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.SpringNeo4jModule)
  while locating neo4j.repositories.AddressCharacteristicRepository
    for field at controllers.loaders.UnitedStatesZipCodesOrg.addrRepo(UnitedStatesZipCodesOrg.java:18)
  while locating controllers.loaders.UnitedStatesZipCodesOrg
    for parameter 6 at router.Routes.<init>(Routes.scala:48)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for parameter 0 at play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:200)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for parameter 4 at play.api.DefaultApplication.<init>(Application.scala:220)
  at play.api.DefaultApplication.class(Application.scala:220)
  while locating play.api.DefaultApplication
  while locating play.api.Application

3 errors]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:170)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:126)
        at scala.Option.map(Option.scala:146)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:126)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:124)
        at scala.util.Success.flatMap(Try.scala:231)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:124)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No primary bean definition for type: interface neo4j.repositories.AddressCharacteristicRepository
  at org.springframework.guice.module.SpringModule.bindConditionally(SpringModule.java:88) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.SpringNeo4jModule)
  while locating neo4j.repositories.AddressCharacteristicRepository
    for field at controllers.loaders.ImportService.addressRepository(ImportService.java:48)
  while locating controllers.loaders.ImportService
    for field at controllers.loaders.DataLoader.importService(DataLoader.java:25)
  while locating controllers.loaders.DataLoader
    for parameter 4 at router.Routes.<init>(Routes.scala:48)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for parameter 0 at play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:200)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for parameter 4 at play.api.DefaultApplication.<init>(Application.scala:220)
  at play.api.DefaultApplication.class(Application.scala:220)
  while locating play.api.DefaultApplication
  while locating play.api.Application

2) No primary bean definition for type: interface neo4j.repositories.AddressCharacteristicRepository
  at org.springframework.guice.module.SpringModule.bindConditionally(SpringModule.java:88) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.SpringNeo4jModule)
  while locating neo4j.repositories.AddressCharacteristicRepository
    for field at controllers.loaders.ImportService.addressRepository(ImportService.java:48)
  while locating controllers.loaders.ImportService
    for field at controllers.loaders.LoadAll.importService(LoadAll.java:33)
  while locating controllers.loaders.LoadAll
    for parameter 5 at router.Routes.<init>(Routes.scala:48)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for parameter 0 at play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:200)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for parameter 4 at play.api.DefaultApplication.<init>(Application.scala:220)
  at play.api.DefaultApplication.class(Application.scala:220)
  while locating play.api.DefaultApplication
  while locating play.api.Application

3) No primary bean definition for type: interface neo4j.repositories.AddressCharacteristicRepository
  at org.springframework.guice.module.SpringModule.bindConditionally(SpringModule.java:88) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.SpringNeo4jModule)
  while locating neo4j.repositories.AddressCharacteristicRepository
    for field at controllers.loaders.UnitedStatesZipCodesOrg.addrRepo(UnitedStatesZipCodesOrg.java:18)
  while locating controllers.loaders.UnitedStatesZipCodesOrg
    for parameter 6 at router.Routes.<init>(Routes.scala:48)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for parameter 0 at play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:200)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for parameter 4 at play.api.DefaultApplication.<init>(Application.scala:220)
  at play.api.DefaultApplication.class(Application.scala:220)
  while locating play.api.DefaultApplication
  while locating play.api.Application

3 errors
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:405)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:400)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:158)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:155)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:155)
        ... 15 common frames omitted

---
## And my build.sbt

name := "play-2.5-sdn-4.1"

organization := "info.unterstein"

version := "1.0-SNAPSHOT"

resolvers ++= Seq(
//  "local maven" at "file://" + Path.userHome.absolutePath + "/.m2/repository",
  "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases",
  "spring snapshots" at "http://repo.spring.io/snapshot",
  "spring milestones" at "http://repo.spring.io/milestone",
  "neo snapshots" at "http://m2.neo4j.org/content/repositories/snapshots"
)

lazy val root = (project in file(".")).enablePlugins(PlayJava)
//lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.6"

libraryDependencies ++= Seq(
  jdbc,
  cache,
  ws,
  specs2 % Test,
//  "org.springframework.data" % "spring-data-neo4j" % "4.1.0.BUILD-SNAPSHOT" changing(),
  "org.springframework.data" % "spring-data-neo4j" % "4.1.0.RC1" changing(),
  "org.neo4j" % "neo4j-ogm-core" % "2.0.0-SNAPSHOT" changing(),
  "org.springframework.guice" % "spring-guice" % "1.0.0.BUILD-SNAPSHOT" changing(),
  "org.webjars" %% "webjars-play" % "2.4.0-2",
  "org.webjars" % "bootstrap" % "3.3.6"
)

// Play provides two styles of routers, one expects its actions to be injected, the
// other, legacy style, accesses its actions statically.
routesGenerator := InjectedRoutesGenerator

//EclipseKeys.projectFlavor := EclipseProjectFlavor.Java           // Java project. Don't expect Scala IDE
EclipseKeys.createSrc := EclipseCreateSrc.ValueSet(EclipseCreateSrc.ManagedClasses, EclipseCreateSrc.ManagedResources)  // Use .class files instead of generated .scala files for views and routes
//EclipseKeys.preTasks := Seq(compile in Compile)                  // Compile the project before generating Eclipse files, so that .class files for views and routes are present

**Comment by DwayneSmurdon** [comment]
Well, it's running now.  Although I cleaned and restarted my project many times, this time I simply rebooted my computer.  That seemed to work.  

However, play seemed to "hang" when starting up.  So, after googling a bit, I ended up making this change:

//fork in run := true
fork in run := false

I noticed that upon reboot, sbt updated some dependencies. Although nothing seemed to be related to DI in any way.  

Just thought I'd leave an update and not waste your time. :)
